POST http://localhost:3003/api/blogs/ HTTP/1.1
content-type: application/json
authorization: bearer

{
    "title": "Yet another blog",
    "author": "Anon-kun",
    "url": "blog-url",
    "likes": 0
}
